services:
  # Frontend Web Application
  web:
    build:
      context: ../../apps/web
      dockerfile: ../../infrastructure/docker/Dockerfile.web
    ports:
      - "3003:80"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3002
    depends_on:
      - api
    networks:
      - chordrectness-network

  # Backend API
  api:
    build:
      context: ../../apps/api
      dockerfile: ../../infrastructure/docker/Dockerfile.api
      target: runner
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CLIENT_URL=http://localhost:3003
      - CHORD_ANALYZER_URL=http://chord-analyzer:8001
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=info
    depends_on:
      - redis
      - chord-analyzer
    networks:
      - chordrectness-network

  # Chord Analyzer Service
  chord-analyzer:
    build:
      context: ../../services/chord-analyzer
      dockerfile: ../../infrastructure/docker/Dockerfile.chord-analyzer
      target: production
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
      - MODEL_PATH=/app/models
      - PYTHONUNBUFFERED=1
    volumes:
      - ../../temp_audio:/app/temp_audio
    networks:
      - chordrectness-network

  # Redis for caching and queues
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - chordrectness-network
    command: redis-server --appendonly yes

  # PostgreSQL for production data
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=chordrectness
      - POSTGRES_USER=chordrectness
      - POSTGRES_PASSWORD=chordrectness
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - chordrectness-network

  # Development tools (only for development)
  dev-tools:
    image: node:18-alpine
    volumes:
      - ../../:/workspace
      - /workspace/node_modules
    working_dir: /workspace
    networks:
      - chordrectness-network
    command: tail -f /dev/null
    profiles:
      - tools

volumes:
  redis-data:
  postgres-data:

networks:
  chordrectness-network:
    driver: bridge
